version: '3.9'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - .env
    volumes:
      - website:/var/www/wordpress
    networks:
      - inception
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - website:/var/www/wordpress
    networks:
      - inception
    restart: always
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    ports:
      - "3306:3306"
    restart: always

volumes:
  database:
    name: ${MARIADB_VOLUME}
  website:
    name: ${WORDPRESS_VOLUME}
networks:
  inception:
    driver: bridge